import { ArticleHeader } from "../_components/ArticleHeader";
import { articleBySlug } from "../_components/articles";

const article = articleBySlug("/docs/bot-wallet")!;

export default function BotWallet() {
  return (
    <div className="space-y-10">
      <ArticleHeader article={article} />

      <section>
        <h2 className="t-h2">Why a dedicated wallet?</h2>
        <p className="mt-3 t-body text-[var(--color-text-muted)]">
          The bot has to sign transactions while you&apos;re not there. The
          familiar &ldquo;Connect Wallet&rdquo; flow from dApps — Phantom
          popup, you approve, the dApp gets a signature — only works when
          you&apos;re sitting in front of the screen. An auto-exit has to fire
          at 3 AM if the price moves, so a wallet adapter is the wrong shape.
        </p>
        <p className="mt-3 t-body text-[var(--color-text-muted)]">
          Instead, the bot keeps an encrypted copy of a Solana key on this
          machine and decrypts it in memory while you have the wallet
          unlocked. That key is what signs the close.
        </p>
      </section>

      <section className="hairline-t pt-10">
        <h2 className="t-h2">The three setup paths</h2>
        <p className="mt-3 t-body text-[var(--color-text-muted)]">
          All three produce the same end state — an encrypted key on disk
          that the bot can use. They differ in where the key starts.
        </p>

        <div className="mt-6 space-y-8">
          <div>
            <h3 className="t-h3 text-[var(--color-text)]">Generate</h3>
            <p className="mt-2 t-body text-[var(--color-text-muted)]">
              The server creates a fresh ed25519 keypair using{" "}
              <code className="t-num text-[var(--color-text)]">node:crypto</code>,
              shows you the base58 secret <em>once</em>, and persists the
              encrypted vault. Save the secret in your password manager — you
              can&apos;t recover it later from this server (only re-derive by
              re-importing into Phantom/Backpack, which requires the secret).
            </p>
            <p className="mt-2 t-body text-[var(--color-text-muted)]">
              Recommended when you don&apos;t already have a hot account to
              repurpose. The secret format is exactly what Phantom and
              Backpack accept under &ldquo;Import private key,&rdquo; so you
              can also add the bot wallet to them as a regular account and
              fund / open positions from familiar UI.
            </p>
          </div>

          <div>
            <h3 className="t-h3 text-[var(--color-text)]">
              Import key (base58)
            </h3>
            <p className="mt-2 t-body text-[var(--color-text-muted)]">
              Paste the private key of an existing account — what Phantom or
              Backpack exports per account. The app accepts the 64-byte base58
              key only, never a seed phrase, so importing exposes <em>one</em>{" "}
              address to this server, not your whole wallet.
            </p>
            <p className="mt-2 t-body text-[var(--color-text-muted)]">
              Convenient when you already keep a hot / operational account
              separate from cold holdings, and you want the bot to manage
              positions you already own. Standard hot-wallet hygiene applies:
              don&apos;t import the account where you store everything.
            </p>
          </div>

          <div>
            <h3 className="t-h3 text-[var(--color-text)]">
              Advanced · JSON
            </h3>
            <p className="mt-2 t-body text-[var(--color-text-muted)]">
              For keys generated by{" "}
              <code className="t-num text-[var(--color-text)]">solana-keygen</code>{" "}
              or kept as JSON byte arrays elsewhere. Same scope as Import key
              — a single account.
            </p>
          </div>
        </div>
      </section>

      <section id="blast-radius" className="hairline-t pt-10">
        <h2 className="t-h2">Blast radius, precisely</h2>
        <p className="mt-3 t-body text-[var(--color-text-muted)]">
          If both your passphrase and the encrypted vault file on this server
          were compromised at the same time, an attacker could move the assets
          held by the address whose key is in the vault. Concretely, that
          means:
        </p>
        <ul className="mt-4 space-y-2 t-body text-[var(--color-text-muted)]">
          <li>
            <span className="text-[var(--color-text)]">Yes:</span> any tokens,
            SOL, or NFTs sitting at <em>that one address</em>.
          </li>
          <li>
            <span className="text-[var(--color-text)]">No:</span> other
            accounts in your Phantom or Backpack — they have different
            private keys.
          </li>
          <li>
            <span className="text-[var(--color-text)]">No:</span> addresses
            derived from your seed phrase — the seed is never sent to this
            server (we only accept per-account keys).
          </li>
          <li>
            <span className="text-[var(--color-text)]">No:</span> wallets on
            other chains, exchange balances, etc.
          </li>
        </ul>
        <p className="mt-4 t-body text-[var(--color-text-muted)]">
          The single-address scope is the design choice that makes this model
          tolerable for a local self-hosted tool. Pair it with the convention
          of keeping a small, operational hot account and you&apos;ve bounded
          the worst case to &ldquo;what was in the hot wallet at the moment
          of compromise.&rdquo;
        </p>
      </section>

      <section id="deleting-the-wallet" className="hairline-t pt-10">
        <h2 className="t-h2">Deleting the wallet</h2>
        <p className="mt-3 t-body text-[var(--color-text-muted)]">
          The Danger zone on{" "}
          <a
            href="/wallet"
            className="text-[var(--color-accent-bright)] hover:underline"
          >
            /wallet
          </a>{" "}
          deletes the encrypted vault file from this server. That removes the
          bot&apos;s ability to sign — nothing else.{" "}
          <strong className="text-[var(--color-text)]">
            The wallet on-chain is unaffected.
          </strong>{" "}
          Tokens, NFTs, and SOL at that address stay where they are; only
          this server loses access.
        </p>
        <p className="mt-3 t-body text-[var(--color-text-muted)]">
          Two valid reasons to delete:
        </p>
        <ul className="mt-4 space-y-3 t-body text-[var(--color-text-muted)]">
          <li>
            <span className="text-[var(--color-text)]">Reset.</span> You want
            to start clean — different account, different passphrase, fresh
            history. Delete the vault, then{" "}
            <em>Set up wallet</em> from the home and pick any of the three
            setup paths again.
          </li>
          <li>
            <span className="text-[var(--color-text)]">Lost passphrase.</span>{" "}
            If you can&apos;t remember the passphrase, the encrypted file is
            useless to you — and to anyone else, as long as it&apos;s a
            strong passphrase. Delete the file and re-import the same key
            with a new passphrase (you still have the secret in your password
            manager or in Phantom/Backpack from when you set it up).
          </li>
        </ul>
        <p className="mt-4 t-body text-[var(--color-text-muted)]">
          Active tasks survive the deletion (they live in SQLite, not the
          vault), but they can&apos;t sign anything until you set up a new
          wallet — they&apos;ll sit in <code className="t-num text-[var(--color-text)]">paused</code>{" "}
          with an explanatory error.
        </p>
      </section>
    </div>
  );
}
